
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: final-project-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: final-project
  type: NodePort
status:
  loadBalancer: {}
